"""Initial migration

Revision ID: 98dfce508b7f
Revises: 
Create Date: 2026-08-06 18:41:40.981735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '98dfce508b7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openalex_id', sa.String(length=255), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=False),
    sa.Column('oa_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_openalex_id'), 'papers', ['openalex_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('parsed_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.create_table('user_paper_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('unread', 'reading', 'reviewed', 'skipped', name='paper_status', native_enum=False, length=20), server_default=sa.text("'unread'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_user_paper_status_user_id_paper_id')
    )
    op.create_index(op.f('ix_user_paper_status_paper_id'), 'user_paper_status', ['paper_id'], unique=False)
    op.create_index(op.f('ix_user_paper_status_user_id'), 'user_paper_status', ['user_id'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('ai_paper_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'paper_id', name='uq_search_results_search_id_paper_id')
    )
    op.create_index(op.f('ix_search_results_paper_id'), 'search_results', ['paper_id'], unique=False)
    op.create_index(op.f('ix_search_results_search_id'), 'search_results', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_search_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_paper_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_user_paper_status_user_id'), table_name='user_paper_status')
    op.drop_index(op.f('ix_user_paper_status_paper_id'), table_name='user_paper_status')
    op.drop_table('user_paper_status')
    op.drop_index(op.f('ix_searches_user_id'), table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_papers_openalex_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###