from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SearchFilters(BaseModel):
    """
    Optional filters provided by the user.
    These are NOT generated by LLM.
    """

    year_from: int | None = None
    year_to: int | None = None
    document_type: str | None = None
    open_access_only: bool = False


class SearchRequest(BaseModel):
    """
    Request schema for paper search endpoint.
    """

    query: str = Field(min_length=1, max_length=2000)
    filters: SearchFilters | None = None
    sort_by: str = "relevance_score:desc"
    page: int = Field(default=1, ge=1)
    per_page: int = Field(default=25, ge=1, le=100)


class PaperTopic(BaseModel):
    """
    Simplified topic representation in search results.
    """

    name: str
    score: float | None = None

    model_config = ConfigDict(from_attributes=True)


class PaperInSearch(BaseModel):
    """
    Paper item as it appears in search results.
    """

    id: UUID
    openalex_id: str
    title: str
    authors: list[str] = []
    publication_year: int | None = None
    type: str | None = None
    cited_by_count: int = 0
    is_oa: bool = False
    source_name: str | None = None
    topics: list[PaperTopic] = []
    status: str = "unread"
    abstract: str | None = None

    model_config = ConfigDict(from_attributes=True)


class SearchResponse(BaseModel):
    """
    Response schema for paper search.
    """

    search_id: UUID
    query_text: str
    ai_summary: str | None = None
    total_count: int = 0
    page: int = 1
    per_page: int = 25
    papers: list[PaperInSearch] = []


class SearchHistoryItem(BaseModel):
    """
    Single search history entry.
    """

    id: UUID
    query_text: str
    result_count: int
    ai_summary: str | None = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SearchHistoryResponse(BaseModel):
    """
    Response schema for search history list.
    """

    searches: list[SearchHistoryItem] = []